const express = require("express")
const sequelize = require("./db")
const cors = require("cors")
const path = require("path")
const database =  require("./db")
const User = require("./models/user")
const jwt = require("jsonwebtoken")
const relation = require("./relations")
database.sync()
const fs = require("fs")
const {formidable} = require("formidable")
